version: '2'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
  backend:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db 
volumes:
  db:
    driver: local