/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.51).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package nsukrpo.backend.controllers.api;

import nsukrpo.backend.model.dtos.CategoryDto;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;

import java.util.List;

@Validated
public interface CategoryApi {

    @GetMapping(value = "/category",
        produces = { "application/json" })
    ResponseEntity<List<CategoryDto>> categoryGet();

}

