/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.51).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package nsukrpo.backend.services.impls;

import nsukrpo.backend.model.dtos.PurchaseDto;
import nsukrpo.backend.services.SalesService;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class SalesServiceImpl implements SalesService {
    @Override
    public List<PurchaseDto> salesGet(Long userId) {
        return null;
    }
}

